name: ApatesCasino
version: @version@
main: de.tk.apatescasino.ApatesCasino
api-version: 1.16
depend: [ Vault, HolographicDisplays, NextEconomy ]
commands:
  casino:
    description: Casino Stuff
    usage: /casino